version: "3.8"
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - API_URL=http://backend:8000
    devices:
      - "/dev/video0:/dev/video0"     # expone la cámara del host
    privileged: true                  # opcional, a veces necesario para permisos
    depends_on:
      - backend
    ports:
      - "8501:8501"
